-- CREATING TABLE PERSON WITH VALUES NAME AND AGE
CREATE TABLE PERSON(
NAME VARCHAR(20),
AGE INT 
);


-- INSERTING VALUES INTO TABLE
INSERT INTO PERSON ( NAME, AGE ) VALUES ('RAM', 21);
INSERT INTO PERSON ( NAME, AGE ) VALUES ('RAVI', 43);
INSERT INTO PERSON ( NAME, AGE ) VALUES ('ABC', 13);

-- DISPLAY ALL VALUES FROM TABLES
SELECT * FROM PERSON;

-- DELETING TABLE AFTER USE
DROP TABLE PERSON;